/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.52).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.exception.NotFoundException;
import io.swagger.model.Reservation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2024-01-04T12:42:16.224399976Z[GMT]")
@Validated
public interface ReservationsApi {

    @Operation(summary = "Deletes reservation", description = "Deletes reservation of room for guest", security = {
        @SecurityRequirement(name = "BasicAuth")    }, tags={ "Reservation" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Reservation is successfully deleted"),
        
        @ApiResponse(responseCode = "404", description = "Reservation not found"),
        
        @ApiResponse(responseCode = "500", description = "An error occured while processing the request. ") })
    @RequestMapping(value = "/reservations/rooms/{roomId}/guests/{guestJMBG}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteReservation(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("roomId") Integer roomId,
                                           @Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("guestJMBG") String guestJMBG) throws NotFoundException;


    @Operation(summary = "Returns reservation", description = "Returns details of reservation with given room and guest", security = {
        @SecurityRequirement(name = "BasicAuth")    }, tags={ "Reservation" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Gets Reservation of Room for Guest", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Reservation.class))),
        
        @ApiResponse(responseCode = "404", description = "Reservation not found"),
        
        @ApiResponse(responseCode = "500", description = "An error occured while processing the request. ") })
    @RequestMapping(value = "/reservations/rooms/{roomId}/guests/{guestJMBG}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Reservation> getReservation(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("roomId") Integer roomId,
                                               @Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("guestJMBG") String guestJMBG) throws NotFoundException;


    @Operation(summary = "Return Reservation", description = "Returns the reservation of room", security = {
        @SecurityRequirement(name = "BasicAuth")    }, tags={ "Reservation" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Fetch Reservaton of Room", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Reservation.class)))),
        
        @ApiResponse(responseCode = "404", description = "Room not found"),
        
        @ApiResponse(responseCode = "500", description = "An error occured while processing the request. ") })
    @RequestMapping(value = "/reservations/rooms/{roomId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Reservation>> getRoomReservations(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("roomId") Integer roomId) throws NotFoundException;


    @Operation(summary = "Makes reservation", description = "Makes reservation for guests", security = {
        @SecurityRequirement(name = "BasicAuth")    }, tags={ "Reservation" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Reservation is successfully made"),
        
        @ApiResponse(responseCode = "404", description = "Room/Guest not found"),
        
        @ApiResponse(responseCode = "500", description = "An error occured while processing the request. ") })
    @RequestMapping(value = "/reservations/rooms/{roomId}/guests/{guestJMBG}",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> saveRoomReservation(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("roomId") Integer roomId,
                                             @Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("roomId") String guestJMBG,
                                             @Parameter(in = ParameterIn.DEFAULT, description = "", schema=@Schema()) @Valid @RequestBody Reservation body) throws NotFoundException, HttpClientErrorException;

}

