/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.52).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.exception.NotFoundException;
import io.swagger.model.Room;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2024-01-04T12:42:16.224399976Z[GMT]")
@Validated
public interface RoomsApi {

    @Operation(summary = "Return Room details", description = "Returns the room details", tags={ "Room" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Fetch Room details", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Room.class))),
        
        @ApiResponse(responseCode = "404", description = "Room not found"),
        
        @ApiResponse(responseCode = "500", description = "An error occured while processing the request. ") })
    @RequestMapping(value = "/rooms/{roomId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Room> getRoom(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("roomId") Integer roomId) throws NotFoundException;


    @Operation(summary = "Return all rooms of Hotel", description = "Returns the rooms that Hotel have", tags={ "Room" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Fetch rooms of Hotel", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Room.class)))),
        
        @ApiResponse(responseCode = "404", description = "Rooms not found"),
        
        @ApiResponse(responseCode = "500", description = "An error occured while processing the request. ") })
    @RequestMapping(value = "/rooms",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Room>> getRooms() throws NotFoundException;

}

